const $=id=>document.getElementById(id);
let current=null,dirty=false,poll=null,busy=false;
const labels={narrative:"Estrutura narrativa",speech:"Falas e sequência",broll:"Imagens de apoio",rhythm:"Ritmo",format:"Formato",duration:"Durações",animation:"Animações"};
async function api(path,method="GET",data){const res=await fetch("/templates/api"+path,{method,headers:{"content-type":"application/json"},...(data?{body:JSON.stringify(data)}:{})});const value=await res.json();if(!res.ok)throw Error(value.error||"Falha na operação");return value;}
async function act(work){if(busy)return;busy=true;$("message").textContent="Processando…";try{await work();$("message").textContent="Atualizado.";}catch(error){$("message").textContent=error.message;}finally{busy=false;}}
async function library(){const {recipes}=await api("");$("library").replaceChildren();for(const r of recipes){const b=document.createElement("button");b.textContent=r.name+" · r"+r.revision+" · "+(r.status==="approved"?"Aprovado":"Rascunho");b.setAttribute("aria-current",String(current?.id===r.id&&current?.revision===r.revision));b.onclick=()=>act(async()=>{if(dirty&&!confirm("Descartar alterações ainda não salvas?"))return;const data=await api("/"+r.id+(r.status==="approved"?"?revision="+r.revision:""));show(data.recipe);});$("library").append(b);}}
function show(r){clearTimeout(poll);current=r;dirty=false;$("detail").hidden=false;$("empty").hidden=true;$("title").textContent=r.name;$("name").value=r.name;$("status").textContent="Revisão "+r.revision+" · "+(r.status==="approved"?"Aprovada por você":r.analysis.status)+" · "+r.analysis.stage+(r.analysis.error?" — "+r.analysis.error:"");
 const src="/templates/api/"+r.id+"/media"+(r.status==="approved"?"?revision="+r.revision:"");if($("reference").getAttribute("src")!==src)$("reference").src=src;
 $("rules").replaceChildren();for(const rule of r.rules){const box=document.createElement("article");box.className="rule";box.dataset.id=rule.id;const h=document.createElement("h3");h.textContent=labels[rule.category]+" · "+({observed:"observado",uncertain:"incerto",unavailable:"indisponível"}[rule.confidence]);const p=document.createElement("p");p.textContent=rule.observation;const label=document.createElement("label");const check=document.createElement("input");check.type="checkbox";check.checked=rule.enabled;label.append(check," Usar esta orientação");const instruction=document.createElement("textarea");instruction.value=rule.instruction;instruction.setAttribute("aria-label","Orientação de "+labels[rule.category]);const times=document.createElement("div");times.className="evidence";for(const e of rule.evidence){const b=document.createElement("button");b.type="button";b.textContent=e.start.toFixed(1)+"–"+e.end.toFixed(1)+"s";b.onclick=()=>{$("reference").currentTime=e.start;$("reference").play().catch(()=>{});};times.append(b);}box.append(h,p,times,label,instruction);$("rules").append(box);}
 const running=r.analysis.status==="running";$("cancel").hidden=!running;for(const id of ["save","analyze","relink"])$(id).disabled=running;$("approve").disabled=r.analysis.status!=="ready"||r.status==="approved";
 if(running)poll=setTimeout(()=>act(async()=>{show((await api("/"+r.id)).recipe);}),1000);
}
$("reference").onerror=()=>{$("message").textContent="Referência indisponível. Use Religar vídeo para localizar o original.";};
$("create").onsubmit=e=>{e.preventDefault();act(async()=>{const data=await api("","POST",{name:$("newName").value});if(data.recipe){show(data.recipe);await library();}});};
$("edit").oninput=()=>{dirty=true;$("approve").disabled=true;};
$("edit").onsubmit=e=>{e.preventDefault();act(async()=>{const rules=current.rules.map(r=>{const box=[...$("rules").children].find(b=>b.dataset.id===r.id);return {...r,enabled:box.querySelector("input").checked,instruction:box.querySelector("textarea").value};});show((await api("/"+current.id,"PATCH",{baseRevision:current.revision,name:$("name").value,rules})).recipe);await library();$("save").focus();});};
$("approve").onclick=()=>act(async()=>{if(dirty)throw Error("Salve suas alterações antes de aprovar.");show((await api("/"+current.id+"/approve","POST",{baseRevision:current.revision})).recipe);await library();});
$("analyze").onclick=()=>act(async()=>{if(!$("consent").checked)throw Error("Marque a autorização de análise externa para continuar.");if(dirty)throw Error("Salve suas alterações antes de analisar.");show((await api("/"+current.id+"/analyze","POST",{baseRevision:current.revision,modelOptIn:true,visualOptIn:true})).recipe);await library();});
$("cancel").onclick=()=>act(async()=>{await api("/"+current.id+"/cancel","POST",{baseRevision:current.revision});show((await api("/"+current.id)).recipe);});
$("relink").onclick=()=>act(async()=>{const data=await api("/"+current.id+"/relink","POST",{baseRevision:current.revision});if(data.recipe){show(data.recipe);await library();}});
act(library);
