export function templateProposalView(proposal,revision){
 const stale=!!proposal&&proposal.baseRevision!==revision;
 return {canAccept:!!proposal&&!stale,stale,lines:proposal?[
  ...(proposal.templateReport||[]).map(r=>({applied:"Aplicado",adapted:"Adaptado",unavailable:"Indisponível"}[r.status])+": "+r.reason),
  ...(proposal.scenes||[]).flatMap(s=>[s.objective,...(s.animationNotes||[]).map(n=>"Pendente: "+n.description+" — "+n.destination)]),
 ]:[]};
}
export function mountTemplates({state,api}){
 const root=document.createElement("section");root.className="template-panel";root.setAttribute("aria-label","Template do projeto");
 root.innerHTML='<h2>Template editorial</h2><p class="muted" id="activeTemplate">Sem template</p><div id="appliedReport" hidden><h3 id="appliedReportTitle"></h3><ul id="appliedReportRules" class="plain"></ul><div id="appliedReportAnims" hidden><h4>Animações pendentes — handoff</h4><ul id="appliedReportAnimList" class="plain"></ul></div></div><label>Receita aprovada<select id="templateChoice"><option value="">Sem template</option></select></label><button type="button" id="refreshTemplates">Atualizar biblioteca</button><label><input id="templateConsent" type="checkbox"> Autorizo analisar os materiais e gerar uma proposta com o provedor configurado (pode haver cobrança).</label><button type="button" id="generateTemplate">Gerar proposta revisável</button><p id="templateStatus" role="status" aria-live="polite"></p><div id="templateCandidate" hidden><h3>Proposta para revisão</h3><p id="templateExplanation"></p><ol id="templateReport"></ol><button type="button" id="acceptTemplate">Aceitar montagem</button><button type="button" id="rejectTemplate">Descartar proposta</button></div>';
 document.getElementById("rail").append(root);
 const $=id=>root.querySelector("#"+id);let busy=false;
 async function refresh(){try{const response=await fetch("/templates/api");const data=await response.json();if(!response.ok)throw Error(data.error);const selected=$("templateChoice").value;$("templateChoice").replaceChildren(new Option("Sem template",""));for(const r of data.recipes.filter(r=>r.status==="approved"))$("templateChoice").append(new Option(r.name+" · r"+r.revision,r.id+":"+r.revision));$("templateChoice").value=selected;}catch(e){$("templateStatus").textContent=e.message;}}
 function render(){const project=state.get("project");const proposal=state.get("templateProposal");const view=templateProposalView(proposal,project?.revision);$("activeTemplate").textContent=project?.template?project.template.name+" · r"+project.template.revision:"Sem template";$("templateCandidate").hidden=!proposal;$("acceptTemplate").disabled=!view.canAccept||busy;$("rejectTemplate").disabled=busy;$("generateTemplate").disabled=busy||!project?.assembly.sources.some(s=>s.included);$("templateExplanation").textContent=view.stale?"A montagem mudou. Gere uma nova proposta.":proposal?.explanation||"";$("templateReport").replaceChildren();for(const text of view.lines){const li=document.createElement("li");li.textContent=text;$("templateReport").append(li);}}
 // Relatório da receita aceita (#68): lê o estado gravado no aceite,
 // direto do payload do projeto — abrir o painel não dispara análise.
 function renderReport(){const report=state.get("templateReport");const box=$("appliedReport");box.hidden=!report||!report.recipe;if(box.hidden)return;$("appliedReportTitle").textContent=`Relatório — ${report.recipe.name} · r${report.recipe.revision}`;const label={applied:"Aplicado",adapted:"Adaptado",unavailable:"Indisponível"};const list=$("appliedReportRules");list.replaceChildren();for(const rule of report.rules){const li=document.createElement("li");li.textContent=`${label[rule.status]}: ${rule.instruction} — ${rule.reason}`;if(rule.sceneIds){for(const id of rule.sceneIds){const b=document.createElement("button");b.type="button";b.textContent=`cena ${id}`;b.onclick=()=>{state.set("selectedScene",id);state.set("view","montagem");};li.append(" ",b);}}else{const s=document.createElement("span");s.className="muted";s.textContent=" · sem cena registrada";li.append(s);}list.append(li);}const anims=$("appliedReportAnims");anims.hidden=!report.animations.length;const al=$("appliedReportAnimList");al.replaceChildren();for(const n of report.animations){const li=document.createElement("li");li.textContent=`${n.description} → ${n.destination} (cena ${n.sceneId})`;al.append(li);}}
 async function action(path,extra={}){if(busy)return;busy=true;render();$("templateStatus").textContent="Processando proposta…";try{const project=state.get("project");const {res,body}=await api.call(path,{method:"POST",body:JSON.stringify({baseRevision:project.revision,...extra}),label:"Template editorial…"});if(!res.ok)throw Error(body.error);if(Object.hasOwn(body,"templateProposal"))state.set("templateProposal",body.templateProposal);$("templateStatus").textContent=path.endsWith("accept")?"Montagem aceita. Assista à prévia antes de aprovar.":"Atualizado.";}catch(e){$("templateStatus").textContent=e.message;}finally{busy=false;render();}}
 $("generateTemplate").onclick=()=>{if(!$("templateConsent").checked){$("templateStatus").textContent="Autorize a análise dos materiais e a geração da proposta para continuar.";return;}const [id,revision]=$("templateChoice").value.split(":");action("/project/template-proposal",{templateId:id||null,templateRevision:id?Number(revision):undefined,modelOptIn:true,visualOptIn:true});};
 $("acceptTemplate").onclick=()=>action("/project/template-accept",{proposalId:state.get("templateProposal")?.id});
 $("rejectTemplate").onclick=()=>action("/project/template-reject",{proposalId:state.get("templateProposal")?.id});
 $("refreshTemplates").onclick=refresh;state.subscribe("project",render);state.subscribe("project",renderReport);state.subscribe("templateProposal",render);state.subscribe("templateReport",renderReport);render();renderReport();refresh();
}
